# Hallmark: Python

Track local files, select data with ParaFrame, download server data, and share catalogs.
Run the cells in order with Hallmark installed.
For commands, see [demo_cli.ipynb](demo_cli.ipynb).

## Setup

All demo files go in a temporary folder.

In [1]:
import os
import tempfile
from pathlib import Path

from hallmark import ParaFrame, Repo

workspace = Path(tempfile.mkdtemp(prefix="hallmark-demo-"))
os.chdir(workspace)
print("Working in", workspace)

Working in /var/folders/kw/p6dm6cw517vcz0jm5nq2zznr0000gn/T/hallmark-demo-le1z2jhx

## Local files

### Create a repository

`Repo.init` creates `.hm` to store the catalog and history.

In [2]:
repo = Repo.init("my-data")
print("catalog folder:", repo.dothm.path)
print("data folder:   ", repo.worktree)

catalog folder: /private/var/folders/kw/p6dm6cw517vcz0jm5nq2zznr0000gn/T/hallmark-demo-le1z2jhx/my-data/.hm
data folder:    /private/var/folders/kw/p6dm6cw517vcz0jm5nq2zznr0000gn/T/hallmark-demo-le1z2jhx/my-data

### Create sample files

These filenames contain spin `a` and angle `i`.

In [3]:
for a in [0, 0.5]:
    for i in [30, 60]:
        (repo.worktree / f"a{a}_i{i}.h5").write_text(f"spin {a}, angle {i}\n")
sorted(path.name for path in repo.worktree.glob("*.h5"))

['a0.5_i30.h5', 'a0.5_i60.h5', 'a0_i30.h5', 'a0_i60.h5']

### Add files

Give a filename pattern. The fields in `{}` become columns in a ParaFrame table.

In [4]:
pf = repo.add("a{a}_i{i}.h5")
pf

          path    a   i
0  a0.5_i30.h5  0.5  30
1  a0.5_i60.h5  0.5  60
2    a0_i30.h5  0.0  30
3    a0_i60.h5  0.0  60

### Check changes

`status()` shows what is staged for the next commit.

In [5]:
repo.status()

{'branch': 'main',
 'staged': {'state': ['config.yml', 'data.tsv', 'meta.yml'],
  'added': ['a0.5_i30.h5', 'a0.5_i60.h5', 'a0_i30.h5', 'a0_i60.h5'],
  'modified': [],
  'deleted': []},
 'worktree': {'modified': [], 'deleted': []},
 'untracked': [],
 'remote_catalog': False}

### Save a version

`commit()` saves the catalog and copies local files into `.hm/objects/`.
`log()` shows the history.

In [6]:
repo.commit("First dataset")
print(repo.log())

commit 87dc0bf2733382c185337b582ce5ea1a579fdbdf
Author: Hallmark Demo <demo@example.invalid>
Date:   Sat Oct 10 19:19:32 2026 -0700

    First dataset

commit eb41213c863fe0a31be2ae6003cc989561f30f04
Author: Hallmark Demo <demo@example.invalid>
Date:   Sat Oct 10 19:19:32 2026 -0700

    Initial commit: local `.hm` repository

`repo.state.data` holds the catalog, including checksums and filename values.

In [7]:
repo.state.data

                                       sha1    a   i
0  b17c3b9a3bf5d3ca963d35fb29334bd4eccd00e6  0.5  30
1  56892f238c71725ed30c42e767772c88c7240d0f  0.5  60
2  d06cfb2ea6f77d6a880b657fb91ec9cf54007a2d    0  30
3  98abc5d60bd8150aeadd6952c93457f0f0a771df    0  60

### Record a change

`add(".")` rescans files using the saved pattern.

In [8]:
(repo.worktree / "a0_i30.h5").write_text("spin 0, angle 30, fixed\n")
repo.add(".")
print(repo.status()["staged"])
repo.commit("Fix a0_i30")

{'state': ['data.tsv'], 'added': [], 'modified': ['a0_i30.h5'], 'deleted': []}

True

### Use a branch

In this version, `checkout(NAME)` creates a missing branch and switches to it.

In [9]:
repo.checkout("only-spin-0")
for path in repo.worktree.glob("a0.5_*.h5"):
    path.unlink()
repo.add(".")
repo.commit("Keep only spin 0")
repo.branches()

{'current': 'only-spin-0', 'names': ['main', 'only-spin-0']}

Switching back to `main` restores its files.

In [10]:
repo.checkout("main")
sorted(path.name for path in repo.worktree.glob("*.h5"))

['a0.5_i30.h5', 'a0.5_i60.h5', 'a0_i30.h5', 'a0_i60.h5']

### Change the pattern

Use `set_config(fmt=...)` for a different filename pattern.

In [11]:
repo.checkout("new-names")
for path in repo.worktree.glob("*.h5"):
    path.unlink()
for i in [30, 60]:
    (repo.worktree / f"b1_i{i}.h5").write_text(f"model b, angle {i}\n")
repo.set_config(fmt="b{b}_i{i}.h5")
repo.add(".")
repo.commit("Switch to b files")
print(repo.state.data)
repo.checkout("main")

                                       sha1  b   i
0  ac7e81dc0768914c44215573be505fffcfe152f8  1  30
1  dc3ee6806b389f1ef3a0cb0ef31bcb7174df2fe9  1  60

True

### Read encoded values

Here, `am0.5` means spin −0.5. Encoding rules currently support `aspin` only.

In [12]:
spins = Repo.init("spins")
for name in ["am0.5_i30.h5", "a0_i30.h5", "a0.5_i30.h5"]:
    (spins.worktree / name).write_text(name)
spins.set_config(fmt="a{aspin}_i{i}.h5", encoding_updates={"aspin": "m([0-9.]+)"})
spins.add("a{aspin}_i{i}.h5", encoding=True)

           path  aspin   i
0   a0.5_i30.h5    0.5  30
1     a0_i30.h5    0.0  30
2  am0.5_i30.h5   -0.5  30

## Select files with ParaFrame

`ParaFrame.parse` reads parameter values from filenames.

In [13]:
pf = ParaFrame.parse("a{a}_i{i}.h5", base_path=repo.worktree)
pf

          path    a   i
0  a0.5_i30.h5  0.5  30
1  a0.5_i60.h5  0.5  60
2    a0_i30.h5  0.0  30
3    a0_i60.h5  0.0  60

Select spin `a = 0`.

In [14]:
pf(a=0)

        path    a   i
2  a0_i30.h5  0.0  30
3  a0_i60.h5  0.0  60

One call with two fields means OR: `a = 0` or `i = 60`.

In [15]:
pf(a=0, i=60)

          path    a   i
1  a0.5_i60.h5  0.5  60
2    a0_i30.h5  0.0  30
3    a0_i60.h5  0.0  60

Two calls mean AND: `a = 0` and `i = 60`.

In [16]:
pf(a=0)(i=60)

        path    a   i
3  a0_i60.h5  0.0  60

You can also use pandas filters.

In [17]:
pf[pf.i > 40]

          path    a   i
1  a0.5_i60.h5  0.5  60
3    a0_i60.h5  0.0  60

## Server data

### Connect to the demo server

The remote examples need SSH access to the demo server and OpenSSH 9.6 or newer.
Add your server details to `~/.ssh/config`:

```
Host hallmark-demo
    HostName <server-address>
    User <your-username>
    IdentityFile ~/.ssh/<your-key-file>
```

Check the connection with `ssh hallmark-demo`, then run `exit`.

In [18]:
import subprocess

subprocess.run(["ssh", "-V"], check=True)
data_url = "ssh://hallmark-demo/srv/hallmark_demo_data"
print("Using", data_url)

Using ssh://hallmark-demo/srv/hallmark_demo_data

OpenSSH_10.5p1, LibreSSL 3.3.6

### Add a remote catalog

`add(URL/PATTERN)` records remote files and checksums without downloading the data.

In [19]:
eht = Repo.init("eht-data")
eht.add(data_url + "/{src}_{day:03d}.txt")
eht.commit("Add archive catalog")
eht.state.data

,path,checksum_algorithm,checksum,size_bytes,mtime,src,day
0,M87_001.txt,sha256,9f63d0da60c5547a643c252f496548c3f3ca3c24f8fa5b...,51,1790578411,M87,1
1,M87_002.txt,sha256,41f61067d19f691617c921e761c51ddc6ac9af0f1851d3...,51,1790578411,M87,2
2,SgrA_001.txt,sha256,af21843d5333d531a37560488b60ad7fbfcf60989031d9...,52,1790578411,SgrA,1
3,SgrA_002.txt,sha256,b7df6c6736a71760f3d6f6defa9b91990a9148106907c3...,52,1790578411,SgrA,2

### Preview a download

`plan_download()` selects files without downloading. `filter` matches filenames.

In [20]:
plan = eht.plan_download(filter="SgrA_*")
print(plan.summary())

2 file(s); 104 bytes; estimated duration: unknown
Source: ssh://hallmark-demo/srv/hallmark_demo_data/
Backend: ssh
Destination: /private/var/folders/kw/p6dm6cw517vcz0jm5nq2zznr0000gn/T/hallmark-demo-le1z2jhx/eht-data

### Download selected files

Pass `approved=True` to download the plan and verify checksums.

In [21]:
eht.download(plan, approved=True)

{'succeeded': 2, 'failed': 0, 'total_bytes': 104, 'errors': []}

Use `all_files=True` for the catalog. Files with matching checksums are skipped.

In [22]:
eht.download(eht.plan_download(all_files=True), approved=True)
sorted(str(path.relative_to(eht.worktree)) for path in eht.worktree.rglob("*.txt"))

['M87_001.txt', 'M87_002.txt', 'SgrA_001.txt', 'SgrA_002.txt']

### Choose a download folder

Use `output_path` to save files outside the repository.

In [23]:
output = workspace / "downloaded-data"
plan = eht.plan_download(output_path=output, filter="M87_*")
eht.download(plan, approved=True)
sorted(path.name for path in output.iterdir())

['M87_001.txt', 'M87_002.txt']

## Share a catalog

Clone from a Git URL or local `.hm` path. The data must be on a server.
Local-file catalogs cannot be cloned in the MVP.

### Catalog only

Use `download=False` to copy the catalog without data.

In [24]:
catalog_only = Repo.clone("eht-data/.hm", "catalog-only", download=False)
sorted(path.name for path in catalog_only.worktree.iterdir())

['.hm']

### Catalog and data

`Repo.clone` downloads by default without a prompt.

In [25]:
full_copy = Repo.clone("eht-data/.hm", "full-copy")
full_copy.download_result

{'succeeded': 4, 'failed': 0, 'total_bytes': 206, 'errors': []}

### Choose whether to download

An `approve` function can check the plan first. This example declines more than two files.

In [26]:
def approve(plan):
    print(plan.summary())
    return plan.file_count <= 2


later_copy = Repo.clone("eht-data/.hm", "later-copy", approve=approve)
print("downloaded:", later_copy.download_result)

4 file(s); 206 bytes; estimated duration: unknown
Source: ssh://hallmark-demo/srv/hallmark_demo_data/
Backend: ssh
Destination: /private/var/folders/kw/p6dm6cw517vcz0jm5nq2zznr0000gn/T/hallmark-demo-le1z2jhx/later-copy
downloaded: None

## Clean up

Remove the temporary demo files.

In [27]:
import shutil

os.chdir(Path.home())
shutil.rmtree(workspace)